-- ─────────────────────────────────────────────────────────────────────────────
-- DR-025b (recovery, 2026-09-24) — corrective sibling: ADD VALUE 'CANCELLED'
--                                    to BillingCertificationStatus enum.
--
-- Why this migration exists as a sibling, not an in-place edit to 20260924100000
-- --------------------------------------------------------------------------------
-- The original DR-025 migration
-- (`20260924100000_dr025_correction_cancelled/migration.sql`) shipped using
-- the lowercase type name `billing_certification_status` for `ALTER TYPE`.
-- Postgres created the enum via Prisma's CREATE TYPE under its QUOTED
-- PascalCase identifier `"BillingCertificationStatus"` (preserve the
-- identifier quoting from the schema), so on the first deploy the migrator
-- hit `42704 — type "billing_certification_status" does not exist` and the
-- migration ended up in the `_prisma_migrations` ledger as a failed /
-- unfinished row.
--
-- Phase-4 P0 policy forbids editing an applied migration in place. Even
-- though this one never applied, the canonical recovery pattern (matching
-- the dr031 leave-constraint + s7 project-attachment recoveries already
-- noted in `start.sh`) is:
--
--   1. Mark the failed row as rolled-back so future `migrate deploy` runs
--      see it as historical (not "in flight") and will skip past it. CI's
--      `Bootstrap resolve (clear errored ledger rows)` step now lists
--      `20260924100000_dr025_correction_cancelled` for one-shot clearing.
--   2. Apply the actual schema change in a NEW sibling migration with a
--      later timestamp. The new file uses the correct PascalCase type
--      identifier, since Prisma CREATE TYPE emits that exact spelling.
--
-- Effect (additive, zero destructive change):
--
--   ALTER TYPE "BillingCertificationStatus" ADD VALUE IF NOT EXISTS 'CANCELLED'.
--
-- Idempotency: the IF NOT EXISTS clause makes a re-run against an
-- already-migrated DB a no-op (matches the dr031 / dr021 / DocumentCategory
-- additive-enum convention used across this repo).
--
-- Existing rows: untouched. DRAFT / CERTIFIED / DISPUTED rows keep their
-- status; the new value is only written by `/cancel-correction` under the
-- same guards (DRAFT-leaf + matching expectedVersion) the original migration
-- shipped with.
--
-- ADD VALUE caveat
-- ----------------
-- Postgres 12+ allows `ALTER TYPE ... ADD VALUE` inside a transaction block,
-- but the new value cannot be used in the SAME transaction it was added.
-- This migration adds the value only; the route that writes it runs in a
-- separate request transaction — same invariant as the original DR-025
-- migration, no extra coordination needed.
-- ─────────────────────────────────────────────────────────────────────────────

ALTER TYPE "BillingCertificationStatus"
  ADD VALUE IF NOT EXISTS 'CANCELLED';
